routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
// TODO 拆分admin为独立模块
Route::get('/', 'IndexController@index')->name('admin');
Route::get('/login', 'AuthController@showLoginForm');
Route::post('/login', 'AuthController@login');

Route::get('/logout', 'AuthController@logout')->name('admin.logout');
Route::post('/logout', 'AuthController@logout');

Route::resource('/user','UserController', ['as' => 'admin']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\FavoriteController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\UserController;

Route::group([
    'middleware' => 'auth',
], function ($router) {
    Route::resource('article.comment', CommentController::class);

    Route::post('/category/update-logo', CategoryController::class . '@updateLogo');

    Route::post('/user/update-avatar', UserController::class . '@updateAvatar');
    Route::get('/home', HomeController::class . '@index')->name('home');

});

Route::get('/', IndexController::class . '@index')->name('index');
Route::get('/test', TestController::class . '@index');

/********************* Auth Routes *********************/
// Authentication Routes...
$this->get('login', LoginController::class . '@showLoginForm')->name('login');
$this->post('login', LoginController::class . '@login');
$this->post('logout', LoginController::class . '@logout')->name('logout');

// Registration Routes...
$this->get('register', RegisterController::class . '@showRegistrationForm')->name('register');
$this->post('register', RegisterController::class . '@register');

// Password Reset Routes...
$this->get('password/reset', ForgotPasswordController::class . '@showLinkRequestForm')->name('password.request');
$this->post('password/email', ForgotPasswordController::class . '@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', ResetPasswordController::class . '@showResetForm')->name('password.reset');
$this->post('password/reset', ResetPasswordController::class . '@reset');

/********************* End *********************/

/** 这是首页 */

Route::resource('/article', ArticleController::class);

Route::get('/category/{id}', ArticleController::class . '@index')->name('category.show');
Route::get('/tag/{id}', ArticleController::class . '@index')->name('tag.show');

app/Models/Article.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Builder;

/**
 * App\Models\Article
 *
 * @property int $id
 * @property string $slug
 * @property string $title
 * @property string $body
 * @property int $user_id
 * @property bool $version
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property int $article_id
 * @property string $type
 * @property bool $is_awesome
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Meta[] $categories
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Comment[] $comments
 * @property-read mixed $display_title
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Tag[] $tags
 * @property-read \App\Models\User $user
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Article whereArticleId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Article whereBody($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Article whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Article whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Article whereIsAwesome($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Article whereSlug($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Article whereTitle($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Article whereType($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Article whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Article whereUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Article whereVersion($value)
 * @mixin \Eloquent
 */
class Article extends Content
{
    protected $table = 'contents';


    protected $next;
    private $previous;

    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope('type', function (Builder $builder) {
            return $builder->where('type', '=', 'article');
        });
        static::created(function($model){
            $model->category();
            $model->categories->each->buildArticleCountCache();
        });
    }
    public function __construct(array $attributes = [])
    {
        $attributes['type'] = 'article';
        parent::__construct($attributes);
    }


    public function previous()
    {
        if ($this->previous === null) {
            $this->previous = $this->where('id', '<', $this->id)->first(['id', 'title']);
        }
        return $this->previous;
    }

    public function next()
    {
        if ($this->next === null) {
            $this->next = $this->where('id', '>', $this->id)->first(['id', 'title']);
        }
        return $this->next;
    }
}

app/Http/Controllers/Api/ArticleController.php
<?php

namespace App\Http\Controllers\Api;

use App\Article;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::getByRandom(100);
        return $articles;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Meta;
use App\Repositories\Content\ArticleRepository;
use App\Models\Tag;
use Illuminate\Http\Request;
use App\Repositories\Criteria\RequestCriteria;

class ArticleController extends Controller
{
    /** @var ArticleRepository $repository */
    protected $repository;

    /**
     * ArticleController constructor.
     * @param ArticleRepository $repository
     */
    public function __construct(ArticleRepository $repository)
    {
        $this->repository = $repository->pushCriteria(app(RequestCriteria::class));
    }

    /**
     * 文章列表，兼容分类、标签、关键词搜索
     *
     * @param Request $request
     * @param ArticleRepository $this->repository
     * @param null $metaId
     * @return \Illuminate\Http\Response
     * @internal param null $id
     */
    public function index(Request $request, $metaId = null)
    {
        $meta = new \stdClass();
        $meta->title = '';

        if (\Route::currentRouteName() == 'article.index') {

        }
        if (\Route::currentRouteName() == 'category.show') {
            $meta = Category::where(is_numeric($metaId) ? 'id' : 'slug', $metaId)->firstOrFail();
            $this->repository->pushCriteria(new \App\Repositories\Criteria\CategoryCriteria($meta));
        }
        if (\Route::currentRouteName() == 'tag.show') {
            $meta = Tag::where(is_numeric($metaId) ? 'id' : 'slug', $metaId)->firstOrFail();
            $this->repository->pushCriteria(new \App\Repositories\Criteria\TagCriteria($meta));
        }



        $titleMap = [
            'article.index' => '全部文章',
            'category.show' => '分类 - ' . $meta->title,
            'tag.show' => '标签 - ' . $meta->title,
        ];

        $pn = $request->get('pn', 20);

        $articles = $this->repository->orderBy('updated_at', 'DESC')->with('comments.user')->with('user')->paginate($pn)->appends($request->query());

        return view('article.index', ['articles' => $articles, 'article_title' => $titleMap[\Route::currentRouteName()]]);
    }


    public function show($id)
    {
        $article = $this->repository->with('comments.user')->find($id);
        return view('article.show', ['article' => $article]);
    }

    public function create()
    {
        $model = $this->repository->model();
        return view('article.edit', [
            'article' => new $model,
            'action' => 'create',
            'method' => 'POST',
            'route' => 'article.store',
            'title' => '发布文章',
        ]);
    }

    public function edit($id)
    {
        return view('article.edit', [
            'article' => $this->repository->find($id),
            'action' => 'edit',
            'method' => 'PUT',
            'route' => 'article.update',
            'title' => '编辑文章',
        ]);
    }

    public function store(Request $request)
    {
        $article = $this->repository->create($request->all() + ['user_id' => \Auth::id()]);
        return $this->success('发布成功', ['article' => $article]);
    }

    public function update(Request $request, $id)
    {
        $this->repository->find($id)->update($request->all());
        return $this->success('保存成功');
    }

    public function destroy($id)
    {
        $this->repository->delete($id);
        return $this->success('删除成功');
    }
}

resources/views/article/edit.blade.php
@extends('layouts.app')
@push('breadcrumbs')
<li class="active">{{ $title }}</li>
@endpush
@section('header')

    <link rel="stylesheet" href="/bower_components/bootstrap3-wysihtml5-bower/dist/bootstrap3-wysihtml5.min.css">
    <style>
        .form-control {
            background-color: rgba(255, 255, 255, 0.12);
            height: inherit;
        }
    </style>
    <meta name="article-id" content="{{ $article->id }}">
@endsection
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-0">
                <div class="app-block">
                    @include('components.breadcrumb')
                    <form class="" role="form" method="POST" action="{{ route($route, $article->id) }}">
                        <div class="row">
                            <div class="col-md-12 col-md-offset-0">
                                {{ csrf_field() }}
                                {!! method_field($method) !!}
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <input id="title" type="text" class="form-control" name="title"
                                                   value="{{ $article->title }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                <textarea style="width: 100%; height: 400px; font-size: 14px; line-height: 18px;"
                                          id="body-input" name="body" hidden>{{ $article->body }}</textarea>
                                </div>
                            </div>


                            <div class="col-md-12 col-md-offset-0">
                                <div class="row">
                                    <div class="col-xs-6">

                                    </div>
                                    <div class="col-xs-6 text-right">
                                        <input class="btn btn-default" type="submit" value="保存">
                                        {{ return_url_field(route('article.index')) }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection


@section('footer')
    <script src="/bower_components/bootstrap3-wysihtml5-bower/dist/bootstrap3-wysihtml5.all.min.js"></script>
    <script>
        $('#body-input').wysihtml5({
            toolbar: {
                fa: true
            }
        }).show();
    </script>
@endsection

resources/views/article/index.blade.php
@extends('layouts.content')
@push('breadcrumbs')
<li class="active">{{ $article_title }}</li>
@endpush

@section('body')

    <div class="col-md-8 col-md-offset-0">
        <div class="app-block">
            @include('components.breadcrumb')
            @include('components.search-form')
            <ul id="articles" class="list-unstyled">
                @foreach($articles as $article)
                    <li style="padding-bottom: 8px">
                        <div>
                            <h4>
                                <a class="" title="{{ $article -> title }}"
                                   href="{{ $article -> showUrl() }}">
                                    {{ $article -> display_title }}
                                </a>
                            </h4>
                            <span style="padding: 4px 8px; margin-right: 8px;" class="bg-info">
                                                <i class="fa fa-comments-o" aria-hidden="true"></i>
                                {{ $article->comments->count() }}
                                            </span>

                            <small>
                                <i class="fa fa-user-o text-warning" aria-hidden="true"></i>
                                <a href="#">{{ $article->user->name }}</a>
                            </small>
                            <small>{{ $article->created_at->diffForHumans() }} 发布</small>

                            @if($article->comments->count())
                                ||
                                <small>
                                    <i class="fa fa-comment-o" aria-hidden="true"></i>
                                    <a href="#">{{ $article->comments->first()->user->name }}</a>
                                </small>
                                <small>{{ $article->comments->first()->updated_at->diffForHumans() }}回复
                                </small>
                            @endif
                        </div>
                    </li>
                @endforeach
            </ul>
            <div class="text-center">
                {{ $articles->links() }}
            </div>
        </div>

    </div>

@endsection
@section('footer')
    <script>
    </script>

@endsection

resources/views/article/show.blade.php
@extends('layouts.content')
@section('header')
    <style>
        #article-field-set {
            font-style: oblique;
            font-size: 0.9em;
            margin: 18px 18px 18px 0;
            border-left: 2px solid #1b6d85;
        }

        .btn-vote {
            padding: 0;
        }
    </style>
    <meta name="article-id" content="{{ $article -> id }}">
@endsection
@section('body')
    <div class="col-md-8 col-md-offset-0">
        <div class="app-block">
        <h2>{{ $article -> title }}</h2>

        <div class="row" id="article-field-set">
            <div class="col-xs-3">
                <span>分类: </span>
                <span>
                            <a href="{{ $article -> category() -> showUrl() }}">
                            {{ $article -> category() -> title }}
                            </a>
                        </span>
            </div>
            <div class="col-xs-3">
                <span>长度: </span>
                <span>{{ mb_strlen($article -> body) }} 字</span>
            </div>
            <div class="col-xs-4">
                <span hidden>标签: </span>
                <ul class="tags list-inline">
                    @foreach($article->tags as $tag)
                        <li>
                            <a href="{{ $tag->showUrl() }}">
                                    <span class="label label-success">
                                        {{ $tag->title }}
                                    </span></a>
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>

        <div class="row action-list">

            <div class="col-md-6">
                @if(\Auth::check() && \Auth::user()->can('manage_contents'))
                    <div>
                        <form class="form-inline" action="{{ route('article.destroy', $article -> id) }}"
                              method="POST">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <a class="btn btn-link" href="{{ route('article.edit', $article -> id) }}">编辑</a>
                            <button class="btn btn-link">删除</button>
                            {{ return_url_field(route('article.index')) }}
                        </form>

                    </div>
                @endif

            </div>
        </div>


        <section id="article-body">
            {!! $article -> body !!}
        </section>
        <div class="article-author">
            <a href="#">
                <img style="padding: 5px;" class="img-circle" width="50" height="50"
                     src="{{ $article->user->avatarUrl }}">
                {{ $article->user->name }}</a>
            <small>{{ $article->created_at->diffForHumans() }} 发布</small>
        </div>
        <hr>
        <ul class="comments list-unstyled">
            @foreach($article['comments'] as $comment)

                <li style="border-bottom: darkcyan solid 1px;">

                    <section style="padding: 10px;">
                        {!! $comment->body !!}
                    </section>
                    <div class="author">
                        <a href="#">
                            <img style="padding: 5px;" class="img-circle" width="50" height="50"
                                 src="{{ $comment->user->avatarUrl }}">
                            {{ $comment->user->name }}</a>
                        <small>{{ $comment->created_at->diffForHumans() }} 回复</small>
                    </div>
                </li>
            @endforeach
        </ul>

        <div class="goto-comment-editor">
            <h4>回复</h4>
            <form id="comment-editor" method="post" action="{{ route('article.comment.store', $article) }}">
                @include('hacker_alert')
                {{ csrf_field() }}
                <div class="form-group">
                    <label class="hidden" for="field-body"></label>
                    @if(\Auth::check())
                        <textarea id="field-body" style="height: 120px;resize:none;" class="form-control"
                                  name="body"></textarea>
                    @else
                        <div id="field-body" style="height: 120px;" class="form-control" name="body">登陆后才可以回复哦
                        </div>
                    @endif
                </div>

                <button>提交</button>
            </form>
        </div>


        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="row">
                    <div class="col-xs-6">
                        上一篇：
                        @if($article -> previous())
                            <a href="{{ $article -> previous() -> showUrl() }}">{{ $article -> previous() -> title }}</a>
                        @else
                            没有了
                        @endif


                    </div>
                    <div class="col-xs-6 text-right">
                        下一篇：
                        @if($article -> next())
                            <a href="{{ $article -> next() -> showUrl() }}">{{ $article -> next() -> title }}</a>
                        @else
                            没有了
                        @endif
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
@endsection


@section('footer')
    {{--// todo 这里为啥要Ajax？？？？--}}
    <script>
        $(document).on('submit', '#comment-editor', function (event) {
            var form = $(event.target);
            var url = form.attr('action');
            var method = form.attr('method');
            var request_data = form.serializeArray();
            $.ajax(url, {
                type: method,
                dataType: 'json',
                data: request_data,
            }).always(function (xhrOrData, status) {
                var response_data = [];
                if (status == 'success') {
                    response_data = xhrOrData;
                } else {
                    response_data = xhrOrData.responseJSON;
                }
                alert(response_data.message);
                if (response_data.status == 'success') {
                    location.reload();
                }
            });
            return false;
        })
    </script>
    <script>

        var currentUserVote = $('#VoteBar').data('currentUserVote');

        renderVote(currentUserVote);

        function renderVote() {

            if (window.currentUserVote > 0) {
                $('#vote-down-btn').removeClass('active');
                $('#vote-up-btn').addClass('active');
            } else if (window.currentUserVote === 0) {
                $('#vote-up-btn').removeClass('active');
                $('#vote-down-btn').removeClass('active');
            } else if (window.currentUserVote < 0) {
                $('#vote-down-btn').addClass('active');
                $('#vote-up-btn').removeClass('active');
            }
        }

        function vote_click(event, self, is_add) {
            $(self).attr("disabled", true);
            event.preventDefault();
            if (is_add) {
                var url = '{{ url('/article/vote') }}';
                var data = {!! json_encode(['article_id'=>$article -> id, 'action' => 'up', '_token' => csrf_token()]) !!};
            } else {
                var url = '{{ url('/article/vote') }}';
                var data = {!! json_encode(['article_id'=>$article -> id, 'action' => 'down', '_token' => csrf_token()]) !!};
            }

            $.ajax({
                type: "POST",
                contentType: "application/json; charset=utf-8",
                url: url,
                data: JSON.stringify(data),
                success: function (data) {
                    window.currentUserVote = data.data.vote;
                    renderVote();
                    $('#vote-up-count').html(data.data.article_up_vote);
                    $('#vote-down-count').html(data.data.article_down_vote);
                    $(self).attr("disabled", false);
                    console.log(data)
                },
                error: function (err) {
                    renderVote(data.data.vote);
                    $(self).attr("disabled", false);
                }
            });

        }

        var ishttps = 'https:' == document.location.protocol ? true : false;

        if (ishttps) {
            var conn = new WebSocket('wss://' + document.domain + '/websocket');
        } else {
            var conn = new WebSocket('ws://' + document.domain + ':8080');
        }

        conn.onopen = function (e) {
            console.log('websocket 连接成功');
        };

        conn.onmessage = function (e) {
            console.log(e.data);
        };
        // 统计阅读时间


        $(function () {

            // 上次滚动条位置
            var last_height = -1;

            setInterval(function () {

                // 如果滚动条没变
                if (document.scrollingElement.scrollTop === last_height) {

                    // 说明他还在看
                    sleep++;
                } else {

                    // 否则他已经往下看了
                    sleep = 0;
                }

                // 记录滚动条位置
                last_height = document.scrollingElement.scrollTop;


                // 5秒看一屏，是正常看的
                if (sleep < 5) {
                    conn.send(JSON.stringify({
                        'article_id': $('meta[name="article-id"]').attr('content'),
                    }));
                } else {
                    // 否则是他没看了，在挂机
                    console.log('挂机，不统计');
                }
            }, 1000)
        });


    </script>
@endsection