routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
// TODO 拆分admin为独立模块
Route::get('/', 'IndexController@index')->name('admin');
Route::get('/login', 'AuthController@showLoginForm');
Route::post('/login', 'AuthController@login');

Route::get('/logout', 'AuthController@logout')->name('admin.logout');
Route::post('/logout', 'AuthController@logout');

Route::resource('/user','UserController', ['as' => 'admin']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\FavoriteController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\UserController;

Route::group([
    'middleware' => 'auth',
], function ($router) {
    Route::resource('article.comment', CommentController::class);

    Route::post('/category/update-logo', CategoryController::class . '@updateLogo');

    Route::post('/user/update-avatar', UserController::class . '@updateAvatar');
    Route::get('/home', HomeController::class . '@index')->name('home');

});

Route::get('/', IndexController::class . '@index')->name('index');
Route::get('/test', TestController::class . '@index');

/********************* Auth Routes *********************/
// Authentication Routes...
$this->get('login', LoginController::class . '@showLoginForm')->name('login');
$this->post('login', LoginController::class . '@login');
$this->post('logout', LoginController::class . '@logout')->name('logout');

// Registration Routes...
$this->get('register', RegisterController::class . '@showRegistrationForm')->name('register');
$this->post('register', RegisterController::class . '@register');

// Password Reset Routes...
$this->get('password/reset', ForgotPasswordController::class . '@showLinkRequestForm')->name('password.request');
$this->post('password/email', ForgotPasswordController::class . '@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', ResetPasswordController::class . '@showResetForm')->name('password.reset');
$this->post('password/reset', ResetPasswordController::class . '@reset');

/********************* End *********************/

/** 这是首页 */

Route::resource('/article', ArticleController::class);

Route::get('/category/{id}', ArticleController::class . '@index')->name('category.show');
Route::get('/tag/{id}', ArticleController::class . '@index')->name('tag.show');

resources/views/admin/index.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                后台首页
                <small>查看和管理用户</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol>
        </section>

        <section class="content">

            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">用户注册曲线</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                </div>
                <!-- /.box-body -->
                <div class="box-footer clearfix">
                    最近7天有<span class="text-red"> {{ \App\Models\User::where('created_at','>',date('Y-m-d H:i:s', strtotime('-7day')))->count() }} </span>个新用户
                </div>
            </div>

        </section>
    </div>
@endsection
@section('footer')
@endsection

resources/views/admin/login.blade.php
@extends('admin::layouts.login')
@section('page_title')后台登录@endsection
@section('header')
<style>
    /* 登录样式 */
    body{
        background-image: -webkit-gradient(radial, 587 -52, 197, 580 -115, 589, from(rgb(104, 91, 95)), to(rgb(67, 66, 102)));
        background-image: url('/images/1158269529265500905.jpg');
        -webkit-background-size: cover;
        -moz-background-size: cover;
        background-size: cover;
        /*color: #E3D3D3;*/
    }
    .login-form{
        float: none;
        padding: 4rem 4rem 2rem;
        overflow: hidden;
        background: rgba(0,0,0,.2);
        /*border-radius: 0.4em;*/
        border: 1px solid #191919;
        box-shadow: inset 0 0 2px 1px rgba(255,255,255,0.08), 0 16px 10px -8px rgba(0, 0, 0, 0.6);
        max-width: 480px;
        position: relative;
        margin: 60px auto 2rem;
    }
    @media (max-width:768px){
        .login-form{
            margin: 40px auto 2rem;
        }
    }
    .login-form::before {
        border-style: none;
        content: "";
        width: 41px;
        height: 35px;
        position: absolute;
        left: 37%;
        top: -88px;
        background-color: red;
        border-radius: 50%;
        box-shadow: 0 0 124px 179px #d8d8d8;
    }
    .login-form::after {
        content: "";
        height: 1px;
        width: 33%;
        position: absolute;
        left: 20%;
        top: 0;
        background: -moz-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);
        background: -ms-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);
        background: -o-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);
        background: -webkit-gradient(linear, 0 0, 100% 0, from(transparent), color-stop(0.25, #444), color-stop(0.5, #b6b6b8), color-stop(0.75, #444), to(transparent));
        /* background: -webkit-linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent); */
        background: linear-gradient(left, transparent, #444, #b6b6b8, #444, transparent);
    }
    .login-form form:nth-child(1)::before {
        content: "";
        width: 250px;
        height: 100px;
        position: absolute;
        top: 0;
        left: 45px;
        -webkit-transform: rotate(75deg);
        -moz-transform: rotate(75deg);
        -ms-transform: rotate(75deg);
        -o-transform: rotate(75deg);
        transform: rotate(75deg);
        background: -moz-linear-gradient(50deg, rgba(255,255,255,0.15), rgba(0,0,0,0));
        background: -ms-linear-gradient(50deg, rgba(255,255,255,0.15), rgba(0,0,0,0));
        background: -o-linear-gradient(50deg, rgba(255,255,255,0.15), rgba(0,0,0,0));
        background: -webkit-linear-gradient(50deg, rgba(255,255,255,0.15), rgba(0,0,0,0));
        background: linear-gradient(50deg, rgba(255,255,255,0.15), rgba(0,0,0,0));
        pointer-events: none;
    }
    .text-animate{
        text-shadow: 1px 1px 1px rgba(255,255,255,0.3);
        background: -moz-linear-gradient(left, rgba(105,94,127,0.54) 0%, rgba(255,92,92,0.57) 15%, rgba(255,160,17,0.59) 27%, rgba(252,236,93,0.61) 37%, rgba(255,229,145,0.63) 46%, rgba(111,196,173,0.65) 58%, rgba(106,132,186,0.67) 69%, rgba(209,119,195,0.69) 79%, rgba(216,213,125,0.7) 89%, rgba(216,213,125,0.72) 100%), -moz-repeating-linear-gradient(-45deg, rgba(255,255,255,0.5), transparent 20px, rgba(255,255,255,0.3) 40px);
        background: -webkit-linear-gradient(left, rgba(105,94,127,0.54) 0%,rgba(255,92,92,0.57) 15%,rgba(255,160,17,0.59) 27%,rgba(252,236,93,0.61) 37%,rgba(255,229,145,0.63) 46%,rgba(111,196,173,0.65) 58%,rgba(106,132,186,0.67) 69%,rgba(209,119,195,0.69) 79%,rgba(216,213,125,0.7) 89%,rgba(216,213,125,0.72) 100%), -webkit-repeating-linear-gradient(-45deg, rgba(255,255,255,0.5), transparent 20px, rgba(255,255,255,0.3) 40px);
        background: -ms-linear-gradient(left, rgba(105,94,127,0.54) 0%,rgba(255,92,92,0.57) 15%,rgba(255,160,17,0.59) 27%,rgba(252,236,93,0.61) 37%,rgba(255,229,145,0.63) 46%,rgba(111,196,173,0.65) 58%,rgba(106,132,186,0.67) 69%,rgba(209,119,195,0.69) 79%,rgba(216,213,125,0.7) 89%,rgba(216,213,125,0.72) 100%), -ms-repeating-linear-gradient(-45deg, rgba(255,255,255,0.5), transparent 20px, rgba(255,255,255,0.3) 40px);
        background: linear-gradient(left, rgba(105,94,127,0.54) 0%,rgba(255,92,92,0.57) 15%,rgba(255,160,17,0.59) 27%,rgba(252,236,93,0.61) 37%,rgba(255,229,145,0.63) 46%,rgba(111,196,173,0.65) 58%,rgba(106,132,186,0.67) 69%,rgba(209,119,195,0.69) 79%,rgba(216,213,125,0.7) 89%,rgba(216,213,125,0.72) 100%), repeating-linear-gradient(-45deg, rgba(255,255,255,0.5), transparent 20px, rgba(255,255,255,0.3) 40px);
        background-size: 300% 100%;
        -webkit-background-clip: text;
        -moz-background-clip: text;
        background-clip: text;
        -moz-border-radius: 90px 15px;
        animation: it-animate 20s infinite;
        -moz-animation: it-animate 20s infinite alternate;    /* Firefox */
        -webkit-animation: it-animate 20s infinite alternate;    /* Safari 和 Chrome */
        -ms-animation: it-animate 20s infinite alternate;    /* Opera */
    }
    @-webkit-keyframes it-animate{
        from {
            background-position: center right, top right;
            color: rgba(39,137,149,0.5);
            -moz-box-shadow: 0px 0px 0px 10px rgba(39,137,149, 0.9);
        }
        to {
            background-position: center left, top left;
            color: rgba(255,255,255,0.1);
            -moz-box-shadow: 0px 0px 0px 10px rgba(255,255,255,0.4);
        }
    }
    .main-content{
        margin: 0;
        padding-top: 3em;
    }
    .fa-lock:before {
        /* password input hack */
        font-size: 1.3em;
    }
    .main-container:before {
        /* body background hack */
        background-color: inherit;
    }
    .page-content{
        /* body background hack */
        background-color: inherit;
    }
    @media (min-width:768px){
        .form-horizontal .control-label{
            text-align:left;
        }
    }
    @media only screen and (max-width: 479px){
        .main-content {
            padding-top: 0;
        }
        .login-form {
            margin: 0 auto;
            margin-bottom: 2em;
            padding: 3rem;
        }
    }
    .form-control{
        border-radius: inherit;
    }
    .btn{
        border-radius: inherit;
    }
</style>
@endsection
@section('content')
    <div class="container">

        <div class="page-header">
            <h1 class="" title="这玩意持续占50%CPU，好玩吧？"><b>{{ config('app.name') }}</b> <small class="hidden-xs">管理后台权限检查</small></h1>
            您在此页面的操作将会被记录并可能触发警报，请谨慎！
        </div>
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="login-container">
                    <div class="login-form">
                        <div id='loadingbar' class="waiting"><dt/><dd/></div>
                        <form class="form-horizontal" role="form" action="" method="post" id="login-form">
                            {{ csrf_field() }}
                            <input name="login_type" value="email" type="hidden">

                            <div class="form-group has-feedback">
                                <div class="col-sm-3">
                                    <label for="email-input" class="control-label">邮箱</label>
                                </div>
                                <div class="col-sm-9">
                                    <input id="email-input" name="email" type="email" class="form-control" placeholder="Email" autofocus>
                                    <i class="glyphicon glyphicon-envelope form-control-feedback"></i>
                                </div>
                            </div>
                            <div class="form-group has-feedback">
                                <div class="col-sm-3">
                                    <label for="password-input" class="control-label">密码</label>
                                </div>
                                <div class="col-sm-9">
                                    <input id="password-input" name="password" type="password" class="form-control" placeholder="Password">
                                    <i class="glyphicon glyphicon-eye-open form-control-feedback"></i>
                                </div>
                            </div>
                            <div class="form-group has-feedback">
                                <div class="col-sm-3">
                                    <label for="verify_code-input" class="control-label">验证码</label>
                                </div>
                                <div class="col-sm-5">
                                <span class="block input-icon input-icon-right">
                                    <input id="verify_code-input" name="verify_code" type="text" class="form-control" placeholder="verify code">
                                    <i class="glyphicon glyphicon-font warning form-control-feedback"></i>
                                </span>
                                </div>
                                <div class="col-sm-4">
                                    <img style="cursor: pointer;" src="{{captcha_src()}}" onclick="this.src='{{ url('captcha/default?') }}' + Math.floor(Math.random()*(100000000-10000000+1)+10000000);" width="100%" height="34" />
                                </div>
                            </div>
                            <div class="space"></div>
                            <div class="form-group">
                                <label class="col-sm-4 text-center">
                                    <input name="remember_time" value="2592000" type="checkbox" class="ace">
                                    <span class="lbl">  记住我</span>
                                </label>
                                <div class="col-sm-8 text-right">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="glyphicon glyphicon-off"></i>
                                        <b>登入</b>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>


    </div>

@endsection

@section('footer')
    <script>
        if ((/webkit/.test(navigator.userAgent.toLowerCase()))) {
            $("h1").addClass("text-animate")
        }
        $('#login-form').validate({
            errorElement: 'div',
            errorClass: 'help-block',
            focusInvalid: false,
            rules: {
                username: {
                    required: true,
                    minlength: 4,
                    email:true
                },
                password: {
                    required: true,
                    minlength: 4
                },
                verify_code: {
                    required: true,
                    rangelength: [4, 4]
                },
            },
            messages: {
                email: {
                    required: '请输入账号',
                    email:'账号需要是email格式',
                },
                password: {
                    required: '请输入密码',
                    minlength: '密码最少4位长度',
                },
                verify_code: {
                    required: '请输入验证码',
                    rangelength: '验证码长度为4',
                },
            },
            highlight: function (e) {
                $(e).closest('.form-group').removeClass('has-info').addClass('has-error');
            },
            success: function (e) {
                $(e).closest('.form-group').removeClass('has-error');//.addClass('has-info');
                $(e).remove();
            },
            errorPlacement: function (error, element) {
                if(element.is(':checkbox') || element.is(':radio')) {
                    var controls = element.closest('div[class*="col-"]');
                    if(controls.find(':checkbox,:radio').length > 1) controls.append(error);
                    else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
                }
                else if(element.is('.select2')) {
                    error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
                }
                else if(element.is('.chosen-select')) {
                    error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
                }
                else {
                    error.insertAfter(element);
                }
            },
        });
    </script>
@endsection

resources/views/admin/nav.blade.php
<!-- sidebar: style can be found in sidebar.less -->
<section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
        <div class="pull-left image">
            <img src="{{ Auth::user()->avatarUrl }}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
            <p>{{ Auth::user()->name }}</p>
            <!-- Status -->
            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
    </div>

    <!-- search form (Optional)TODO 菜单搜索 -->
    <form action="#" method="get" class="sidebar-form" hidden>
        <div class="input-group">
            <input type="text" name="q" class="form-control" placeholder="Search...">
            <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
    </form>
    <!-- /.search form -->

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
        <li class="header">菜单</li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="{{ route('admin') }}"><i class="fa fa-calculator"></i> <span>主页</span></a></li>
        <li class="treeview">
            <a href="#"><i class="fa fa-users"></i> <span>用户</span>
                <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
                <li><a href="{{ route('admin.user.index') }}"><i class="fa fa-list-ul"></i> <span>查看</span></a></li>
                <li><a href="{{ route('admin.user.index') }}"><i class="fa fa-plus"></i> <span>创建</span></a></li>
            </ul>
        </li>


        <li><a href="#"><i class="fa fa-link"></i> <span>Another Link</span></a></li>
        <li class="treeview">
            <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span>
                <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu">
                <li><a href="#">Link in level 2</a></li>
                <li><a href="#">Link in level 2</a></li>
            </ul>
        </li>
    </ul>
    <script type="text/javascript">
        /* 导航加上活动类 */
        (function(){
            // 闭包，立即执行，给侧边导航栏添加active状态
            var $this = $('.sidebar-menu a[href="' + location.href + '"]').first();
            var parent_li = $this.parent("li");
            $this.find('i').addClass('text-blue');
            parent_li.addClass('active');

            parent_ul = parent_li.parent('ul');
            if (parent_ul.is('.treeview-menu')){
                parent_ul.addClass('menu-open').show();
                var checkElement = parent_li.parent().parent("li.treeview");
                checkElement.addClass('menu-open');
            }
        })();


    </script>
    <!-- /.sidebar-menu -->
</section>
<!-- /.sidebar -->
  

resources/views/admin/pagination.blade.php
@if ($paginator->hasPages())
    <ul class="pagination pagination-sm no-margin pull-right">
        <!-- Previous Page Link -->
        @if ($paginator->onFirstPage())
            <li class="disabled"><span>&laquo;</span></li>
        @else
            <li><a href="{{ $paginator->previousPageUrl() }}" rel="prev">&laquo;</a></li>
        @endif

        <!-- Pagination Elements -->
        @foreach ($elements as $element)
            <!-- "Three Dots" Separator -->
            @if (is_string($element))
                <li class="disabled"><span>{{ $element }}</span></li>
            @endif

            <!-- Array Of Links -->
            @if (is_array($element))
                @foreach ($element as $page => $url)
                    @if ($page == $paginator->currentPage())
                        <li class="active"><span>{{ $page }}</span></li>
                    @else
                        <li><a href="{{ $url }}">{{ $page }}</a></li>
                    @endif
                @endforeach
            @endif
        @endforeach

        <!-- Next Page Link -->
        @if ($paginator->hasMorePages())
            <li><a href="{{ $paginator->nextPageUrl() }}" rel="next">&raquo;</a></li>
        @else
            <li class="disabled"><span>&raquo;</span></li>
        @endif
    </ul>
@endif