routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
// TODO 拆分admin为独立模块
Route::get('/', 'IndexController@index')->name('admin');
Route::get('/login', 'AuthController@showLoginForm');
Route::post('/login', 'AuthController@login');

Route::get('/logout', 'AuthController@logout')->name('admin.logout');
Route::post('/logout', 'AuthController@logout');

Route::resource('/user','UserController', ['as' => 'admin']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\FavoriteController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\UserController;

Route::group([
    'middleware' => 'auth',
], function ($router) {
    Route::resource('article.comment', CommentController::class);

    Route::post('/category/update-logo', CategoryController::class . '@updateLogo');

    Route::post('/user/update-avatar', UserController::class . '@updateAvatar');
    Route::get('/home', HomeController::class . '@index')->name('home');

});

Route::get('/', IndexController::class . '@index')->name('index');
Route::get('/test', TestController::class . '@index');

/********************* Auth Routes *********************/
// Authentication Routes...
$this->get('login', LoginController::class . '@showLoginForm')->name('login');
$this->post('login', LoginController::class . '@login');
$this->post('logout', LoginController::class . '@logout')->name('logout');

// Registration Routes...
$this->get('register', RegisterController::class . '@showRegistrationForm')->name('register');
$this->post('register', RegisterController::class . '@register');

// Password Reset Routes...
$this->get('password/reset', ForgotPasswordController::class . '@showLinkRequestForm')->name('password.request');
$this->post('password/email', ForgotPasswordController::class . '@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', ResetPasswordController::class . '@showResetForm')->name('password.reset');
$this->post('password/reset', ResetPasswordController::class . '@reset');

/********************* End *********************/

/** 这是首页 */

Route::resource('/article', ArticleController::class);

Route::get('/category/{id}', ArticleController::class . '@index')->name('category.show');
Route::get('/tag/{id}', ArticleController::class . '@index')->name('tag.show');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }} - {{ config('app.sub_name') }}</title>

    <!-- Styles -->
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/bower_components/jquery-editable-select/dist/jquery-editable-select.min.css" rel="stylesheet">
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script src="/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/bower_components/jquery-editable-select/dist/jquery-editable-select.min.js"></script>

    <!-- Scripts -->
    <script>
        window.laravel = {};
        window.laravel.csrf_token = document.getElementsByName('csrf-token')[0].content;
        $.ajaxSetup({headers: {'X-CSRF-TOKEN': window.laravel.csrf_token}});
    </script>

    <style>
        .breadcrumb {
            padding: 0;
            margin-bottom: 10px;
            list-style: none;
            background-color: inherit;
            border-radius: 0;
        }

        .app-block {
            background-color: #fff;
            padding: 10px 15px;
            margin-bottom: 10px;
        }
        .app-block img{
            max-width: 100%;
        }
        .app-search-box {

        }
    </style>
    @yield('header')
</head>
<body id="app">
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#app-navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ route('index') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->
            <ul class="nav navbar-nav">
                {{--
                <li>
                    <a href="{{ url('/category') }}">
                        分类
                    </a>
                </li>
                --}}
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->

            </ul>
        </div>
    </div>
</nav>
<div class="main" style="margin-bottom: 20px;">
    @yield('content')
</div>
<hr>

@include('layouts.foot')
<script src="/js/app.js"></script>
<script>
    console.log("如发现xss或任何其他类型漏洞或安全隐患，请到 'https://github.com/shellus/shcms' 提Issue，感谢您对开源做出的贡献 :)");
</script>
@yield('footer')
</body>
</html>

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }} - {{ config('app.sub_name') }}</title>

    <!-- Styles -->
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/bower_components/jquery-editable-select/dist/jquery-editable-select.min.css" rel="stylesheet">

    <!-- Scripts -->
    <script src="/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/bower_components/jquery-editable-select/dist/jquery-editable-select.min.js"></script>

    <!-- Scripts -->
    <script>
        window.laravel = {};
        window.laravel.csrf_token = document.getElementsByName('csrf-token')[0].content;
        $.ajaxSetup({headers: {'X-CSRF-TOKEN': window.laravel.csrf_token}});
    </script>

    <style>
        .breadcrumb {
            padding: 0;
            margin-bottom: 10px;
            list-style: none;
            background-color: inherit;
            border-radius: 0;
        }

        .app-block {
            background-color: #fff;
            padding: 10px 15px;
            margin-bottom: 10px;
        }
        .app-block img{
            max-width: 100%;
        }
        .app-search-box {

        }
    </style>
    @yield('header')
</head>
<body id="app">
    @yield('content')
@yield('footer')
</body>
</html>

resources/views/layouts/content.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        @yield('body')
        <div class="col-md-4">
            <div class="app-block">
                <h3>功能</h3>
                <ul class="">
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">登录</a></li>
                        <li><a href="{{ url('/register') }}">注册</a></li>
                    @else
                        <li>
                            <a href="{{ url('/home') }}">
                                登录为：{{ Auth::user()->name }}
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('article.create') }}">
                                发布文章
                            </a>
                        </li>
                        <li>
                            <a href="{{ url('/logout') }}"
                               onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                注销
                            </a>

                            <form id="logout-form" action="{{ url('/logout') }}" method="POST"
                                  style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
        <div class="col-md-4">
            <div class="app-block">
                <h3>分类</h3>
                @include('components.category', ['categories' => app(\App\Repositories\Content\CategoryRepository::class)->TagTopList()])
            </div>
        </div>
        <div class="col-md-4">
            <div class="app-block">
                <h3>标签</h3>
                @include('components.tag', ['categories' => app(\App\Repositories\Content\TagRepository::class)->TagTopList()])
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/layouts/foot.blade.php
<footer class="footer">
    <div class="container">
        <div class="row hidden-xs">
            <dl class="col-sm-2 site-link">
                <dt>网站相关</dt>
                <dd><a href="/about">关于我们</a></dd>
                <dd><a href="/tos">服务条款</a></dd>
                <dd><a href="/faq">帮助中心</a></dd>
                <dd><a href="/repu">声望与权限</a></dd>
                <dd><a href="/markdown">编辑器语法</a></dd>
                <dd><a href="//weekly.segmentfault.com/">每周精选</a></dd>
                <dd><a href="/app">App 下载</a></dd>
                <dd><a href="/community">社区服务中心</a></dd>
            </dl>
            <dl class="col-sm-2 site-link">
                <dt>联系合作</dt>
                <dd><a href="/contact">联系我们</a></dd>
                <dd><a href="/hiring">加入我们</a></dd>
                <dd><a href="/link">合作伙伴</a></dd>
                <dd><a href="/press">媒体报道</a></dd>
                <dd><a href="https://board.segmentfault.com/">建议反馈</a></dd>
            </dl>
            <dl class="col-sm-2 site-link">
                <dt>常用链接</dt>
                <dd>
                    <a href="//chrome.google.com/webstore/detail/segmentfault-%E7%AC%94%E8%AE%B0/pjklfdmleagfaekibdccmhlhellefcfo"
                       target="_blank">笔记插件: Chrome</a></dd>
                <dd><a href="//addons.mozilla.org/zh-CN/firefox/addon/sf-note-ext/" target="_blank">笔记插件:
                        Firefox</a></dd>
                <dd>订阅：<a href="/feeds">问答</a> / <a href="/feeds/blogs">文章</a></dd>
                <dd><a href="//mirrors.segmentfault.com/" target="_blank">文档镜像</a></dd>
                <dd><a href="//segmentfault.com/blog/interview" target="_blank">社区访谈</a></dd>
                <dd><a href="//segmentfault.com/d-day" target="_blank">D-DAY 技术沙龙</a></dd>
                <dd><a href="//segmentfault.com/hackathon" target="_blank">黑客马拉松 Hackathon</a></dd>
                <dd><a href="//namebeta.com/" target="_blank">域名搜索注册</a></dd>
                <dd><a href="https://shop165859711.taobao.com/" target="_blank">周边店铺</a></dd>
            </dl>
            <dl class="col-sm-2 site-link">
                <dt>关注我们</dt>
                <dd><a href="//github.com/SegmentFault" target="_blank">Github</a></dd>
                <dd><a href="//twitter.com/segment_fault" target="_blank">Twitter</a></dd>
                <dd><a href="http://weibo.com/segmentfault" target="_blank">新浪微博</a></dd>
                <dd><a href="//segmentfault.com/blog/segmentfault_team" target="_blank">团队日志</a></dd>
                <dd><a href="//segmentfault.com/blog/segmentfault" target="_blank">产品技术日志</a></dd>
                <dd><a href="//segmentfault.com/blog/community_admin" target="_blank">社区运营日志</a></dd>
                <dd><a href="//segmentfault.com/blog/segmentfault_news" target="_blank">市场运营日志</a></dd>
            </dl>
            <dl class="col-sm-4 site-link" id="license">
                <dt>内容许可</dt>
                <dd>除特别说明外，用户内容均采用 <a rel="license" target="_blank"
                                      href="https://creativecommons.org/licenses/by-nc-nd/4.0/">知识共享署名-非商业性使用-禁止演绎
                        4.0 国际许可协议</a> 进行许可
                </dd>
                <dd>本站由 <a target="_blank"
                           href="https://www.upyun.com/?utm_source=segmentfault&amp;utm_medium=link&amp;utm_campaign=upyun&amp;md=segmentfault">又拍云</a>
                    提供 CDN 存储服务
                </dd>
            </dl>
        </div>
        <div class="copyright text-center">
            Copyright © 2011-2017 SegmentFault. 当前呈现版本 17.01.23<br>
            <a href="http://www.miibeian.gov.cn/" rel="nofollow">浙ICP备 15005796号-2</a> &nbsp;
            <a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33010602002000"
               rel="nofollow">浙公网安备 33010602002000号</a>
        </div>
        <p class="text-center">
            <a class="js__view--selector hidden-sm hidden-md hidden-lg" data-action="mobile"
               href="javascript:;">移动版</a>
            <a class="js__view--selector hidden-sm hidden-md hidden-lg" data-action="desktop"
               href="javascript:;">桌面版</a>
        </p>
    </div>
</footer>