routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
// TODO 拆分admin为独立模块
Route::get('/', 'IndexController@index')->name('admin');
Route::get('/login', 'AuthController@showLoginForm');
Route::post('/login', 'AuthController@login');

Route::get('/logout', 'AuthController@logout')->name('admin.logout');
Route::post('/logout', 'AuthController@logout');

Route::resource('/user','UserController', ['as' => 'admin']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\FavoriteController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\UserController;

Route::group([
    'middleware' => 'auth',
], function ($router) {
    Route::resource('article.comment', CommentController::class);

    Route::post('/category/update-logo', CategoryController::class . '@updateLogo');

    Route::post('/user/update-avatar', UserController::class . '@updateAvatar');
    Route::get('/home', HomeController::class . '@index')->name('home');

});

Route::get('/', IndexController::class . '@index')->name('index');
Route::get('/test', TestController::class . '@index');

/********************* Auth Routes *********************/
// Authentication Routes...
$this->get('login', LoginController::class . '@showLoginForm')->name('login');
$this->post('login', LoginController::class . '@login');
$this->post('logout', LoginController::class . '@logout')->name('logout');

// Registration Routes...
$this->get('register', RegisterController::class . '@showRegistrationForm')->name('register');
$this->post('register', RegisterController::class . '@register');

// Password Reset Routes...
$this->get('password/reset', ForgotPasswordController::class . '@showLinkRequestForm')->name('password.request');
$this->post('password/email', ForgotPasswordController::class . '@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', ResetPasswordController::class . '@showResetForm')->name('password.reset');
$this->post('password/reset', ResetPasswordController::class . '@reset');

/********************* End *********************/

/** 这是首页 */

Route::resource('/article', ArticleController::class);

Route::get('/category/{id}', ArticleController::class . '@index')->name('category.show');
Route::get('/tag/{id}', ArticleController::class . '@index')->name('tag.show');

app/Models/User.php
<?php namespace App\Models;

use App\Notifications\ResetPasswordNotification;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;
/**
 * App\User
 *
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property string $remember_token
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $unreadNotifications
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereEmail($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User wherePassword($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereRememberToken($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property string $api_token
 * @property string $register_ip
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Role[] $roles
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereApiToken($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereRegisterIp($value)
 * @property integer $avatar_id
 * @property-read \App\Models\File $avatar
 * @property-read mixed $avatar_url
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereAvatarId($value)
 * @property-read mixed $role_name
 */
class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'register_ip','api_token',
    ];

    protected $visible = [
        'id', 'name', 'email','api_token',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
//    protected $hidden = [
//        'password', 'remember_token',
//    ];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function avatar(){
        return $this->belongsTo('App\Models\File');
    }

    public function getAvatarUrlAttribute(){
        if(!$this->avatar){
            return asset('images/no_avatars/1.png');
        }
        return $this -> avatar -> url;
    }
    public function getRoleNameAttribute(){
        if(!$this->roles){
            return '无用户组';
        }
        return $this->roles->first()->display_name;
    }

    public function roles()
    {
        return $this->belongsToMany('App\Models\Role');
    }

    /**
     * 汉化找回密码邮件内容
     * @param string $token
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use App\Service\UserService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

use App\Http\Requests;

class UserController extends Controller
{

    /** @var  Model $modelClass */
    protected $modelClass = User::class;
    protected $service;
    protected $trans;
    protected $name;
    protected $view;

    /**
     * UserController constructor.
     */
    public function __construct(UserService $service)
    {
        $this->trans = trans("model.{$this -> modelClass}");
        $this->service = $service;
        $this->name = $this->trans['name'];
        $this->view = new \View();


//        $this->view->offsetSet('trans',$this->trans);
    }


    public function index()
    {
        return view("admin::{$this->name}/index", ['trans' => $this->trans]);
    }

    public function create()
    {
        $model = new User();
        return view("admin::{$this->name}/edit", ['model' => $model, 'trans' => $this->trans]);
    }

    public function store()
    {
        $this->service->create();
    }

    public function destroy($id)
    {
        $rows = User::findOrFail($id)->delete();
        return $this->success('删除成功');
    }

    public function edit(User $user)
    {
        return view("admin::{$this->name}/edit", ['model' => $user, 'trans' => $this->trans]);
    }

    public function update(Request $request, User $user)
    {

        $this->validate($request, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255',
        ]);
        $params = $request->all();
        $user->name = data_get($params, 'name');
        $user->email = data_get($params, 'email');
        $user->api_token = data_get($params, 'api_token');
        if ($user->save()) {
            return redirect(route('admin.user.index'));
        }
        return redirect()->back()->withInput()->withErrors(trans('common.edit.failed'));

    }

    public function show(User $user)
    {

    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\File;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function updateAvatar(Request $request)
    {
        $user = \Auth::user();
        $file = $request->file('avatar');

        if(!$file->isValid()){
            return $this->fail('上传失败' . $file -> getErrorMessage());
        }

        File::updateUserAvatarByUploadedFile($user, $file);

        return $this->success('头像上传成功');
    }
}

resources/views/admin/user/create.blade.php
@extends('admin::user.layout')
@section('box')
<div class="row">
    <div class="col-md-8">
        <div class="box">
            <div class="box-header with-border text-right">
                <h3 class="box-title">修改用户</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <form class="form-horizontal">
                    {{ csrf_field() }}
                    @foreach(array_keys($model->toArray()) as $name)
                        <input type="text" name="{{ $name }}" value="{{ $model->$name }}">
                    @endforeach

                    <button class="btn btn-primary">保存</button>
                </form>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin::user.layout')
@section('box')
    <div class="row">
        <div class="col-md-8">
            <div class="box">
                <div class="box-header with-border text-right">
                    <h3 class="box-title">修改用户</h3>
                </div>
                <!-- /.box-header -->
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="box-body">
                    <form class="form-horizontal" action="{{route('admin.user.update',['user'=>$model])}}"
                          method="post">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        @foreach(array_keys($model->toArray()) as $name)
                            <input type="text" name="{{ $name }}" value="{{ $model->$name }}">
                        @endforeach

                        <button class="btn btn-primary">保存</button>
                    </form>
                </div>
                <!-- /.box-body -->
                <div class="box-footer clearfix">
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin::user.layout')
@section('box')
    <div class="box">
        <div class="box-header with-border text-right">
            {{--<h3 class="box-title">用户列表</h3>--}}
            <a class="btn btn-primary margin-r-5" href="{{ route('admin.user.create') }}"><i class="fa fa-plus"></i> 新增 </a>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table class="table table-bordered">
                <tr>
                    <th style="width: 10px">#</th>
                    <th>用户名</th>
                    <th>邮箱</th>
                    <th>注册时间</th>
                    <th>Actions</th>
                </tr>
                <?php $models = \App\Models\User::paginate();?>
                @forelse($models as $model)
                    <tr>
                        <td>{{ $model->id }}.</td>
                        <td>{{ $model->name }}</td>
                        <td>{{ $model->email }}</td>
                        <td>{{ (new \Carbon\Carbon($model->created_at))->diffForHumans() }}</td>
                        <td>
                            <a class="text-success" title="查看" href="{{ route('admin.user.show',$model->id) }}"><i class="fa fa-eye"     ></i></a>&nbsp;&nbsp;
                            <a class="text-warning" title="修改" href="{{ route('admin.user.edit',$model->id) }}"><i class="fa fa-pencil"  ></i></a>
                            <form method="POST" class="inline" action="{{ route('admin.user.destroy',$model->id) }}">
                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}
                                <button class="btn-link text-danger" title="删除" href=""><i class="fa fa-trash-o" ></i></button>
                            </form>&nbsp;&nbsp;
                        </td>
                    </tr>
                @empty
                    没有任何内容哦
                @endforelse
            </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
            {{ $models->links('admin::pagination') }}
        </div>
    </div>
@endsection

resources/views/admin/user/layout.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                用户
                <small>查看和管理用户</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol>
        </section>

        <section class="content">

            @yield('box')

        </section>
    </div>
@endsection
@section('footer')
@endsection